Volunteer Iowa Site/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Volunteer_Iowa_Site.Models;
using Volunteer_Iowa_Site.DAL;
using Volunteer_Iowa_Site.Filters;

namespace Volunteer_Iowa_Site.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class LogController : Controller
    {
        private LogContext db = new LogContext();
        private GenericFunctions gen = new GenericFunctions();
        //
        // GET: /Log/

        public ActionResult Index()
        {
            var log = db.Log.Include(l => l.Event).Include(l => l.Orginization).Include(l => l.UserProfile);
            int LoggedinUserId  = gen.GetUserID();

            IQueryable<Log> custQuery =
                from id in db.Log
                where id.userId == LoggedinUserId
                select id;

            int totalHours = 0;
            if (custQuery.Any())
            {
                foreach (var userLog in custQuery.ToList())
                {
                    totalHours = totalHours + userLog.hoursLogged;
                }
            }
            ViewBag.logHours = totalHours;

            double percents = ((double)totalHours / (double)50) * 100;
            ViewBag.percent = percents;
            //return View(log.ToList());
            return View(custQuery.ToList());
        }

        public ActionResult All()
        {
            int totalHours = 0;

            foreach (var userLog in db.Log.ToList())
            {
                totalHours = totalHours + userLog.hoursLogged;
            }
            
            ViewBag.logHours = totalHours;

            return View(db.Log.ToList());
        }


        //
        // GET: /Log/Details/5

        public ActionResult Details(int id = 0)
        {
            Log log = db.Log.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        //
        // GET: /Log/Create

        public ActionResult Create()
        {
            ViewBag.eventID = new SelectList(db.Event, "eventID", "Name");
            ViewBag.orgID = new SelectList(db.Org, "orgID", "orgName");
            //ViewBag.userId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Log/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Log log)
        {
            if (ModelState.IsValid)
            {
                /*
                if (log.logID == 0 || db.Log.Find(log.logID) != null)
                {
                    int count = db.Log.Count<Logs>();
                
                    log.logID = count++;
                }*/
                log.userId = gen.GetUserID();

                db.Log.Add(log);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.eventID = new SelectList(db.Event, "eventID", "Name", log.eventID);
            ViewBag.orgID = new SelectList(db.Org, "orgID", "orgName", log.orgID);
            ViewBag.userId = new SelectList(db.UserProfiles, "UserId", "UserName", log.userId);
            return View(log);
        }

        //
        // GET: /Log/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Log log = db.Log.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            ViewBag.eventID = new SelectList(db.Event, "eventID", "Name", log.eventID);
            ViewBag.orgID = new SelectList(db.Org, "orgID", "orgName", log.orgID);
            ViewBag.userId = new SelectList(db.UserProfiles, "UserId", "UserName", log.userId);
            return View(log);
        }

        //
        // POST: /Log/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Log log)
        {
            if (ModelState.IsValid)
            {
                db.Entry(log).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.eventID = new SelectList(db.Event, "eventID", "Name", log.eventID);
            ViewBag.orgID = new SelectList(db.Org, "orgID", "orgName", log.orgID);
            ViewBag.userId = new SelectList(db.UserProfiles, "UserId", "UserName", log.userId);
            return View(log);
        }

        //
        // GET: /Log/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Log log = db.Log.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        //
        // POST: /Log/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Log log = db.Log.Find(id);
            db.Log.Remove(log);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Volunteer Iowa Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="header-top-color"> </div>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">
                        <a href="/">
                            <img src="/Content/themes/base/images/v-iowa.svg" />
                        </a>
                    </p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                </div>
            </div>
        </header>
   
        <div id="body">

            <nav class="main-nav">
            <a class="menu-action-link" href="@Url.Action("Index", "Home")"><span  class="icon-home" aria-hidden="true" data-icon="H"></span>Home</a>
            <a class="menu-action-link" href="@Url.Action("About", "Home")"><span  class="icon-cogs" aria-hidden="true" ></span>About</a>
            <a class="menu-action-link" href="@Url.Action( "Index","Log")"><span class="icon-quill" aria-hidden="true" /></span>Log</a>
            </nav>
            <!--
            <nav class="main-nav">
                <ul id="menu">
                    <li class="menu-link"><a class="menu-action-link" href="@Url.Action("Index", "Home")"><span aria-hidden="true" data-icon="&#x21;"></span>Home</a></li>
                    <li class="menu-link"><a class="menu-action-link" href="@Url.Action("About", "Home")"><span aria-hidden="true" data-icon="&#x22;"></span>About</a></li>
                    <li class="menu-link"><a class="menu-action-link" href="@Url.Action("Log", "Home")"><span aria-hidden="true" data-icon="&#x23;"></span>Log</a></li>
                    <!--<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { @class = "test" })</li>
                </ul>
            </nav>
            -->
           <!-- @RenderSection("featured", required: false) -->
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                    <p>&copy; @DateTime.Now.Year - <a href="http://www.volunteeriowa.org/">Volunteer Iowa</a></p>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>